pre-commit:
  # run sequentially: build website, then stage the generated files so
  # they are included in the user's commit
  parallel: false
  commands:
    website-build:
      run: pnpm --filter website run build.static-local
    add-website-dist:
      run: |
        git add website/dist || true
